# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cafcd6765b82462d56c95e6b85ddd90af36164e4fa878a431910362c7a4b01596f821b72de915f05e48a3822cf0b2a18df5e2951d72c28d29f21a6ebaeea98d

test:
  secret_key_base: 53db7c9476737e71e50675bd227213562fe5977451827c817f3ed5062aa4f0bf9c7673daa68875f692301352403ab132fcc00d928a1f98e25f6c92ea0b275992

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
